### ISSUE TITLE
Include basic programming

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#104]
Programming principles and logic are becoming increasingly important for students in Kenya. 
I would like to add a basic programming environment (scratch, blockly, or something similar) to the ElimuPi so students can be introduced to programming via a browser.

**Comment by pieterhoekstra** [comment]
I guess this is a request for a new part of the Admin interface? I can have
a more thorough look into the suggested, starting with Blockly.

Op di 14 mrt. 2023 09:17 schreef Joost Dam ***@***.***>:

**Comment by alonsovidales** [comment]
We could put this in the web interface, you access the home and we have a new section at the level of the wikipedia, kolibri and so on 🤔
If you want I can take care of this one, it seems a good one for start familiarising with how everything works, they could be installed with `npm` from ansible and it could be just adding a loader page and a link to it.
It would be nice to have some offline tutorials or something, I can take a look at that.

**Comment by joostdam** [comment]
Sounds good!

Joost Dam
Founder & Director DEAN
+31 6 24657094<tel:+31624657094>
[https://www.dean.ngo/wp-content/uploads/2020/11/dean-logo.jpg]<https://www.dean.ngo/>
Snelliuslaan 10
1222 TE | Hilversum
The Netherlands
+31 20 7073377<tel:+31207073377>
[https://www.dean.ngo/wp-content/uploads/2020/11/logo-PC-DONATIE_250x43-1.jpg]<https://www.pc-donatie.nl/>

**Comment by joostdam** [comment]
Not the admin, but the public part of the web interface.

Joost Dam
Founder & Director DEAN
+31 6 24657094<tel:+31624657094>
[https://www.dean.ngo/wp-content/uploads/2020/11/dean-logo.jpg]<https://www.dean.ngo/>
Snelliuslaan 10
1222 TE | Hilversum
The Netherlands
+31 20 7073377<tel:+31207073377>
[https://www.dean.ngo/wp-content/uploads/2020/11/logo-PC-DONATIE_250x43-1.jpg]<https://www.pc-donatie.nl/>

**Comment by pieterhoekstra** [comment]
Would be nice if a student serializes and saves / loads his or her own
projects independent of the used device

Op di 14 mrt. 2023 21:45 schreef Alonso Vidales ***@***.***>:

**Comment by joostdam** [comment]
That indeed would be nice. As we don't offer login functionality for students right now (nor want to do that), we could choose to save their projects on a separate external USB disk.

**Comment by alonsovidales** [comment]
PR for Scratch: https://github.com/DEAN-ngo/elimupi/pull/105

By the moment I think that we can go by this one, it is super complete and it is fully offline, it also allows to save in local the project and upload it to continue, it has step by step tutorials for kids and it allows to create games and other stuff that could be very engaging.

I still have to check if everything, included the video tutorials, are offline or if not how to make them offline.

I will send another PR in `ElimuPi-Web-Interface` to add the link.

How do you do to create the icons? do we have any graphic designer or preferred tool?

**Comment by alonsovidales** [comment]
ok, PR updated: #105 

Now we have a script that downloads all the video tutorials and converts them to mp4 so they can be played from the same server without needing an internet connection. The videos directory adds 672M to the image, but they are very good and necessary in order to understand how the system works.

I also had to patch the JSX that embeds the media player in order to serve the videos, this may cause some compatibility issues in the future if Scratch GUI updates that specific file, so something to keep in mind. We also have to keep the videos.json file updated, but I expect very little changes in these files since the last time they were updated was about 4 years ago.

I still have to figure out how to download the tutorial projects, I will work on that now.

**Comment by alonsovidales** [comment]
It seems that the projects are just missing in their repo too, I just cut an issue to them: https://github.com/LLK/scratch-gui/issues/8824

**Comment by alonsovidales** [comment]
PR for the link: https://github.com/DEAN-ngo/ElimuPi-Web-Interface/pull/16

I'm not sure how to add the translations, the script seems to be failing:
```
➜ ~/personal/ElimuPi-Web-Interface (104-scratch-gui) ./i18n.sh nl_NL ./translations
Extracting and updating translations
sed: 1: "./translations/messages ...": invalid command code .
```

**Comment by joostdam** [comment]
We have a graphic designer. I will ask him to design a button/icon.

**Comment by joostdam** [comment]
Updating the translations is done using poedit (https://poedit.net/). This tool generates the needed files as well.

**Comment by alonsovidales** [comment]
> We have a graphic designer. I will ask him to design a button/icon.

Thank you! I added a crappy one that I found with a free license, it doesn't looks too bad, but the color is a bit off.

> Updating the translations is done using poedit (https://poedit.net/). This tool generates the needed files as well.

Done 👍
I added the translations to all the languages, but after I run the `./updateAllTranslations.sh` script I see that other translations were missing so they are also part of the Pull Request as also a fix for the translations in the landing page.

**Comment by alonsovidales** [comment]
Merged the PR for the Ansible changes, we still have to merge the frontend changes. Do you have any update regarding to the icon @joostdam ?

**Comment by joostdam** [comment]
I get the icons this evening and will send them to you.

Sent by mobile device
________________________________

**Comment by alonsovidales** [comment]
I sent the PR some weeks ago for the frontend part with the icons: https://github.com/DEAN-ngo/ElimuPi-Web-Interface/pull/16
Can I merge or do I have to wait for a reviewer? 🤔

**Comment by joostdam** [comment]
Can you help me download the amended version? I will install it on my ElimuPi and do a review.

**Comment by alonsovidales** [comment]
Sure, in order to apply the changes, in your terminal (Mac/Linux):
```
git clone git@github.com:DEAN-ngo/ElimuPi-Web-Interface.git
cd ElimuPi-Web-Interface
git checkout 104-scratch-gui
rsync --rsync-path="sudo rsync" -avz * pi@elimupi:/var/www/html
```

Then in the browser open: http://start.elimupi.online/assets/css/main.css and do `command + r` to expire the cache.

It should look like:

<img width="1439" alt="Screen Shot 2023-05-10 at 08 57 06" src="https://github.com/DEAN-ngo/elimupi/assets/1468785/c61ef873-a466-4ddf-ad13-bb72ceac4ebb">

**Comment by joostdam** [comment]
so far so good, I guess I also need to update the nginx settings and add scratch.elimupi.online domain, or do you just want feedback on the design?

**Comment by alonsovidales** [comment]
The domain is already done in the other PR: https://github.com/DEAN-ngo/elimupi/pull/105/files#diff-fa09cab8bca026bce800334de03efa70e678be640d31c35c7f9ed0d51b55df22R5 it was merged.
I'm going to merge the UI one 👍 thanks!

**Comment by joostdam** [comment]
Instead of 50x50 pixels can you make the icons in the menubar 30x30 pixels?
#navi img:not(.realSize) {
    width: 30px;
    height: 30px;
    position: relative;
    top: 0.5rem;
}

Can you add the scratch icon as a big icon as well?

**Comment by joostdam** [comment]
ah ok, I am using the last image that was made without these new "merges".

**Comment by alonsovidales** [comment]
Done the 30px thingy: https://github.com/DEAN-ngo/ElimuPi-Web-Interface/pull/18

<img width="1313" alt="Screen Shot 2023-05-10 at 20 22 41" src="https://github.com/DEAN-ngo/elimupi/assets/1468785/18cd869d-580c-45f6-ae28-30691bf88ac0">

**Comment by joostdam** [comment]
![image](https://github.com/DEAN-ngo/elimupi/assets/32640087/48965ec5-5538-44a1-bb18-76d373979b2f)
Unfortunately, the scratch version has not yet reached the latest image. I'll ask Techforce to bake a fresh one.

**Comment by ltoning** [comment]
@joostdam @alonsovidales  do you agree to close this issue?  
Scratch programming is now included within the release ElimuPi_Image_2023-05-03-raspios-bullseye-arm64_lite_Release_3.3.0.img.xz released on 12 May 2023

**Comment by joostdam** [comment]
yes sure!
