### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#110]
When connecting a wireless device to the new Elimupi (with the latest image 3.3.0) the devices (tested on android phone and tablet with Chrome browsers) cannot open the interface. 

I can access the pages with my laptop where I configured the hosts file manually. 

That suggest that the problem is with the DNS of the elimupi.

**Comment by ltoning** [comment]
Seems that DNS ( dnsmasq) is delayed or interfered when the Pi is booting up.
This seems to be caused by the extensive loading of the scratch-gui via nmp.

**Comment by ltoning** [comment]
@joostdam shall we close this one as the issue its caused by having a LAN connection via ethernet?
DNS resolution via AP/Wifi will not work in that case.

**Comment by joostdam** [comment]
@ltoning, it worked in the previous version and is very useful when testing. If we can have this feature back, I prefer that.

**Comment by ltoning** [comment]
@joostdam I fully agree with this.
 I will get a fix out to address this issue.

**Comment by alonsovidales** [comment]
I think that the root cause was not loading the `scratch-gui` and it was fixed, nope? if not let me know and I can take a look at it 👍

**Comment by ltoning** [comment]
Root cause of this issue was a mixed setup of using dhcpdcd and udhcpcd together and having nog forwarding rules.
Bug Fixed in #117

**Comment by ltoning** [comment]
closing
