### ISSUE TITLE
Define requirements for Internet access

### ISSUE THREAD

**Issue by DEANpeterV** [DEAN-ngo/elimupi#13]
Document the requirements
- Hardware
- Software
- Functionality

**Comment by marcobruining** [comment]
Een (langzaam) toenemend aantal scholen heeft een centrale internetverbinding. Ik zou graag scenario’s ontwikkelen voor het gebruik van die verbindingen voor de ElimuPi. Te denken valt aan:
-	Binnenhalen update bestanden als een ElimuPi online komt. 
-	Verzenden logfiles als een ElimuPi online is.
-	Verzenden en binnenhalen van mail per batch.

**Comment by joostdam** [comment]
When developing scenarios for internet access, we can use these points of departure:

-	Internet access will each year become more widely available among schools
-	Prices will drop
-	4G is a viable alternative for certain tasks (or as the first step)
-	The ElimuPi is never connected permanently to an Internet connection

We can distinguish different applications of an internet connection.
a.	To collect status reports about the health of the ElimuPi
b.	To collect usage reports 
c.	To update/upgrade the ElimuPi software
d.	To distribute new content
e.	To provide internet access to the users

Use Case A
In between on-site training sessions DEAN wants to distribute assignments to the teachers through ElimuOnline or as a Kolibri lesson to further stimulate them to apply their new skills.
Use Case B
DEAN wants to regularly collect status reports about the health of the ElimuPi and usage statistics.
Use Case C
DEAN wants to be able to update the software of the ElimuPi’s to the newest image without physically having to visit the school.
Use Case D
DEAN wants to be able to distribute new content to schools. This can be .zim files for Kiwix or new or updated Kolibri Channels.

**Comment by joostdam** [comment]
@DEANpeterV , I suggest we use this issue as a point of departure for the new ElimuPi - Connect project that we agreed on creating on GitHub.

**Comment by marcobruining** [comment]
@joostdam Can this issue be closed?

**Comment by joostdam** [comment]
Yes indeed
