### ISSUE TITLE
Let the Pi setup a VPN connection

### ISSUE THREAD

**Issue by marcobruining** [DEAN-ngo/elimupi#20]
Do dit naar een bekende server

**Comment by joostdam** [comment]
@marcobruining , what is the purpose of this issue?

**Comment by marcobruining** [comment]
@joostdam This ticket was raised with the creation of logging/metrics in mind. When a connection to the internet would come available, the Pi should create a vpn connection to some central server to upload the logging/metrics. I think this has become obsolete by the introduction of the Pi Connect.

**Comment by joostdam** [comment]
You are right, I'll close this issue
