### ISSUE TITLE
Add all packages defined in python script to ansible code

### ISSUE THREAD

**Issue by marcobruining** [DEAN-ngo/elimupi#22]
Check and verify if all the packages which are defined in the Python script are added to the ansible file for installing the packages > https://github.com/DEANpeterV/elimupi2.0/blob/ansible/hackathon/roles/common/tasks/packages.yml

Instructions:
- Can be added to `common`  role and to the file `pacakges.yml` 
- create your own branch from hackathon and if it is working create a pull request to merge back into hackathon
- add comments where needed to Ansible.

**Comment by ltoning** [comment]
All package install references defined in python script [ElimuPi_installer.py](https://github.com/DEAN-ngo/elimupi/blob/v2.0.1/ElimuPi_installer.py) have been included in the current leading Ansible install for Elimupi.
Makes the python script installer obsolete.
