### ISSUE TITLE
Move all Kolibri related configuration/user data to external hdd

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#24]
Kolibri maakt gebruik van content bestanden die op de "content" disk staan in de map "kolibri". Op basis van deze content kan een docent/coach in Kolibri lesplannen maken en deze beschikbaar maken voor klassen (ook door de docent zelf te definiëren) en leerlingen.  Het lijkt erop dat in de huidige opzet deze data niet op content disk worden weggeschreven maar een plek krijgen op de sd kaart.

Uitgezocht moet worden waar Kolibri deze data opslaat en deze standaard lokatie wijzigen naar een map op de content/kolibri hdd.

**Comment by joostdam** [comment]
Kan deze met prioriteit worden opgepakt?

**Comment by pieterhoekstra** [comment]
`kolibri manage content movedirectory /mnt/content/kolibri`

**Comment by joostdam** [comment]
Het gros van de content staat inderdaad in /mnt/content/kolibri, echter als ik lessen aanmaak binnen Kolibri en de content schijf aan een andere ElimuPi hang dan zijn die niet meer zichtbaar. Het lijkt er dus op dat deze informatie in een aparte database wordt opgeslagen die nog niet verplaatst is naar de content-schijf.

**Comment by otaconix** [comment]
Het is ons tijdens de hackaton gelukt om dat handmatig voor elkaar te krijgen, en wel als volgt:

1. In `/etc/kolibri/nginx.d/099-user.conf` de verwijzing naar `/home/pi/.kolibri` om te zetten naar `/mnt/content/kolibri-home`
2. In `/etc/kolibri/daemon.conf` de waarde `KOLIBRI_HOME` gezet op `/mnt/content/kolibri-home`
3. In `/etc/init.d/kolibri-server` wordt `KOLIBRI_USER_HOME` (weet niet zeker of dat de naam van de variabele is) niet gezet op `KOLIBRI_HOME`, wat raar is. Dus, pas het aan zodat het gelijk is aan `KOLIBRI_HOME`

NB: Het kan zijn dat `uwsgi` niet meer wil starten omdat er nog een PID-file is blijven hangen. Verwijder dan `/var/run/kolibri-server/uwsgi.pid`.
