### ISSUE TITLE
Switch Raspberry OS to 64 bit version

### ISSUE THREAD

**Issue by DEANpeterV** [DEAN-ngo/elimupi#36]

**Comment by ltoning** [comment]
Ansible playbook supports the latest Raspberry OS 64 bit.

[https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-04-07/2022-04-04-raspios-bullseye-arm64-lite.img.xz](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-04-07/2022-04-04-raspios-bullseye-arm64-lite.img.xz
)
Raspberry Pi OS Lite
Release date: April 4th 2022
System: 64-bit
Kernel version: 5.15
Debian version: 11 (bullseye)
Size: 270MB

**Comment by DEANpeterV** [comment]
Hoi,

Kan een build beschikbaar worden gemaakt om te testen?

Tevens een vraag: Kan er een handleiding worden gemaakt hoe je het beste een build kunt maken?

Peter Venis
DEAN

Tel: + 31 (0) 6 55163871
Digital Education Africa Network | Unleashing Potential |www.dean.ngo<http://www.dean.ngo/> | ***@***.******@***.***>
Snelliuslaan 10 | 1222 TE Hilversum | The Netherlands<https://maps.google.com/?q=Snelliuslaan+11+%7C+1222+TB+Hilversum+%7C+The+Netherlands&entry=gmail&source=g> | +31 20 707 3377<tel:+31%2020%20707%203377>
