### ISSUE TITLE
Research Pi400 possibilities

### ISSUE THREAD

**Issue by marcobruining** [DEAN-ngo/elimupi#37]
Is it possible to set up a Pi 400 as an ElimuPi with a desktop environment attached? The Pi 400 can then be connected to a projector or screen to present centrally in the classroom and also offers the possibility to serve as an access point. In addition, the desktop environment can also be used to work with office apps and educational apps. 
pi400
- client for elimupi
- pi + keyboard and mouse (costs)
- desktop
- or chromebook?

**Comment by marcobruining** [comment]
@joostdam Is this still relevant?
For the Pi400 this would be a valid location for info and costs: https://www.sossolutions.nl/raspberry-pi-400-kit-alles-in-een-pc?gclid=CjwKCAjwjMiiBhA4EiwAZe6jQwvGAY9gcIx4ZfWkzcxRF2tJH_cioJFB94CI0PWxWwJn2H4mmBtedBoC9JAQAvD_BwE
We do have to make some changes to the pi creation process, as there is no GUI (raspian desktop) in the image.
Are the desktop/chromebook still valid options with the elimupi connect in mind?

**Comment by joostdam** [comment]
The Chromebooks are not a valid option anymore. They proof pretty expensive, and they depend on a consistent internet connection to work flawlessly. 

I am still convinced that a PI400 with a projector can be a very interesting addition for schools. Or an entry-level solution for schools.

**Comment by alonsovidales** [comment]
Hey!
I already have a Pi400, if you want I can try to prepare the image.
Is the idea to have a completely separate image that will connect to an ELimuPi server or will this device be the server too?
If we make it the server we can just add Xorg + Firefox and it shouldn't weight too much, it will also be way faster and we can save some money, the only problem is that the Pi 400 came in only one configuration with 4GB of RAM that for what I've been trying is ok for using it as server, but adding a browser can get a bit sort, but I can always try and see how it looks.

For projectors, there are some by 50-60 euros but according to the reviews they are terrible, the cheapest I found with decent reviews could be:
- https://www.amazon.nl/-/en/TOPVISION-Projector-Supports-Display-Compatible/dp/B07PYVLN3W/
It is 88 euros with speakers and for what it says the light is LED, I used to have an incandescent one in Spain and when it is too hot the bulb dies of the projector overheats too fast that could be a problem in Kenya.
We will also need a mini HDMI to HDMI converter that is 7 euros.

Another alternative with speakers by 46 is:
 - https://www.amazon.nl/-/en/Portable-Projector-Theater-Compatible-Smartphone/dp/B0BQLFWV9J
it has some bad reviews but some good ones too. This one has only 3000 lumenes compared to the other one that is 7000, for a classroom I would get the 7000 one.

Someone comments in the questions that the polarised filter may get burned and they couldn't find spare ones. This could be something to have in consideration mostly in hot weather.

**Comment by alonsovidales** [comment]
The installation of Firefox is 26MB for openbox (the window manager) + 55MB for Firefox only.

I'm thinking that we could install it by default and using a script launch Firefox every-time a HDMI device is detected and kill Firefox 2 minutes after the device is disconnected. The browser will open http://start.elimupi.online/ by default.
This way we can have the same image, it will only take 81MB of space more but no memory or CPU consumption unless a screen is plugged in and it can be used for normal Raspberry Pi installations as well, so if someone want to use a normal one in the same way they could just add a USB keyboard 🤔
I will try to get it done to see how it looks like...

**Comment by alonsovidales** [comment]
PR for this: https://github.com/DEAN-ngo/elimupi/pull/111

This adds about 100MB to the system, but it doesn't use any CPU or memory until the HDMI is connected. It is using `udev` in order to detect when the device is connected.

The audio works by HDMI and it is able to play the videos and so on, it is a bit slow, but very usable.

It uses Openbox that is a very light Widnow Manager and it seems to work quite well and it is very light.
