### ISSUE TITLE
Redirect all internet links to status page when no internet available

### ISSUE THREAD

**Issue by marcobruining** [DEAN-ngo/elimupi#38]
The different kiwix wiki's do contain some external links. As a user, I want to be redirected to a default page with a short explanation why I can't access this page when I click on an external link.

**Comment by alonsovidales** [comment]
404 landing page:

![Image](https://user-images.githubusercontent.com/1468785/232198898-21930fba-16bf-4415-9ea0-0bc1132a4c73.png)

I'm redirecting everything there when there is no internet connection

**Comment by alonsovidales** [comment]
I think that the fordwading is not enabled in the Raspberry Pi, right now when I connect to the raspberry I don't have internet access, adding:
```
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
```
to do the trick

**Comment by alonsovidales** [comment]
PRs:
 - https://github.com/DEAN-ngo/elimupi/pull/109
 - https://github.com/DEAN-ngo/ElimuPi-Web-Interface/pull/17

**Comment by ltoning** [comment]
Hi @alonsovidales , 

dnsmasq service fails to start with message : bad option at line 2 of /etc/dnsmasq.d/custom-dns.conf

It's due to the ttl line in the script : 
echo -e "address=/#/10.11.0.1\nttl=5" > /etc/dnsmasq.d/custom-dns.conf

Should work when we change it to : 
echo -e "address=/#/10.11.0.1\n**local-ttl**=5" > /etc/dnsmasq.d/custom-dns.conf

**Comment by alonsovidales** [comment]
Ahh, I didn't get that when testing 🤦‍♂️ Thanks for finding it out!
PR for this: https://github.com/DEAN-ngo/elimupi/pull/115

**Comment by ltoning** [comment]
@alonsovidales can we close this one? tested it and works fine.
