### ISSUE TITLE
Migrate web-interface installation/configuration steps from Python script to Ansible

### ISSUE THREAD

**Issue by jer0enA** [DEAN-ngo/elimupi#40]
Migrate all the steps from the Python script related to the web interface to ansible. It can be found in the function `def install_web_interface():` 

Instructions:
- Maybe as a separate Ansible role?
- create your own branch from hackathon and if it is working create a pull request to merge back into hackathon
- add comments where needed to Ansible.

**Comment by michaelhuisman** [comment]
how to upload?
