### ISSUE TITLE
Make use of virtual pi for development

### ISSUE THREAD

**Issue by marcobruining** [DEAN-ngo/elimupi#44]
To make it easier to develop the Ansible code it will be useful to have a virtual Pi. With this virtual Pi it will be easier to run the Ansible code and to start fresh. With a physical Pi this means you need to flash a clean OS again to the SD-card and then do the initial setup before you can run your ansible code. In this virtual pi it should be just a entering a command to start fresh and a few minutes later you should have it up and running. 

Some attempts are already done to get it working. There is a branch called `dockerpi`. This will make use of the tool called dockerpi and that can be found on https://github.com/lukechilds/dockerpi and https://github.com/clutroth/dockerpi3 . The tools make it possible to run QEMU from docker. 

Another option could be something like this https://wiki.debian.org/QemuUserEmulation, check with @ltoning (Laurens Töning) for more information. 

Some requirements:

- It should emulate at least a Pi 3b
- A GUI is not needed for the Pi
- Possible to access the Pi via ssh to run Anisble.
- Would be nice of some additional ports can also be reach to check at the end the running webservices.
- Using the same base image as we use in the packer pipeline, for now `https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-05-28/2021-05-07-raspios-buster-armhf.zip` 
- Run on Windows and Linux. If Windows turns out to be difficult maybe in a VM or another option could be the cloud.

The initial idea is to use it for running Ansible code but if it turns out that the virtual Pi also can be used for testing the webinterface and the installed packages that would be verry nice.

**Comment by ltoning** [comment]
QEMU support for Raspberry PI4 isn't available at this time https://www.qemu.org/docs/master/system/arm/raspi.htmlQ
QEMU raspi3b emulation works but it just to slow in the process of development for the elimupi via Ansible.
Also not all features of the Pi can be emulated.
