### ISSUE TITLE
Migrate remaining steps from Python script to Ansible

### ISSUE THREAD

**Issue by jer0enA** [DEAN-ngo/elimupi#46]
Migrate all remaining steps from the Python script to Ansible. 

- `def install_citadel():`
- `def setup_content_disk():` 
- `def add_content_disk_to_fstab():`
- `def install_usbmount():` 
- `def install_wifi():`

Instructions:
- Can be added to `common`  role.
- create your own branch from hackathon and if it is working create a pull request to merge back into hackathon
- add comments where needed to Ansible.

**Comment by joostdam** [comment]
![Image](https://user-images.githubusercontent.com/32640087/175956500-1d4bbab9-4c33-4153-9336-b763ebfcd274.png)

**Comment by ltoning** [comment]
host file adjusted to URL names listed at https://github.com/DEAN-ngo/elimupi/blob/main/README.md#user-access
migrate steps completed
def install_citadel():  | not needed any longer
def setup_content_disk():  | done
def add_content_disk_to_fstab():  | done
def install_usbmount(): | done
def install_wifi(): | done

**Comment by ltoning** [comment]
Completed
