### ISSUE TITLE
504 Gateway Time-out in Kiwix

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#84]
When searching in Kiwix (for instance on "Carbon dioxide") kiwix comes back with a 504 gateway time-out. Is it possible to allow a longer server response time before a time-out occurs? This happens mainly when you use the search form on the kiwix dashboard as Kiwix then searches through all the wiki entries.

**Comment by ltoning** [comment]
@joostdam @DEANpeterV  is this still an issue when using the elimupi release 3.1.0 or later  ?

**Comment by joostdam** [comment]
Solved in the latest update/upgrade
