### ISSUE TITLE
Load zim files in Kiwix

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#86]
After copying new .zim files to the content disk, you should load them by restarting nginx. 

Both `sudo systemctl restart nginx`  or `sudo systemctl stop nginx -> sudo systemctl start nginx` do not make a difference. 

Only after a full reboot of the ElimuPi the new .zim files are visible.

**Comment by DEANpeterV** [comment]
Restart : 'sudo systemctl restart kiwix'

Error in kiwix-start.pl script to not correctly build the library.xml file.

**Comment by joostdam** [comment]
Changing the file locations to /mnt/content/wiki/ in /var/kiwix/bin/kiwix-start.pl still results in a 502 error on the webpage.
![image](https://user-images.githubusercontent.com/32640087/156783969-5bf6f850-b77f-4624-b6e4-a5c215f04660.png)
