### ISSUE TITLE
Use latest version of Raspian 32 bit

### ISSUE THREAD

**Issue by marcobruining** [DEAN-ngo/elimupi#91]
Currently we are using the Raspian version last used with the Python installation.
Use latest version of 32 bit (Buster)
https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-legacy

**Comment by joostdam** [comment]
![Image](https://user-images.githubusercontent.com/32640087/175950120-1a4be4d2-8c09-4023-968c-946d0fdf7ef1.png)

**Comment by joostdam** [comment]
![Image](https://user-images.githubusercontent.com/32640087/175950456-08f1f8aa-905f-44f0-88e5-b7b2f20ed1c3.png)

**Comment by ltoning** [comment]
Ansible playbook now based  on latest Raspberry Pi OS 

[https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-04-07/2022-04-04-raspios-bullseye-armhf-lite.img.xz](https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-04-07/2022-04-04-raspios-bullseye-armhf-lite.img.xz)

Raspberry Pi OS Lite

    Release date: April 4th 2022
    System: 32-bit
    Kernel version: 5.15
    Debian version: 11 (bullseye)
    Size: 297MB

**Comment by ltoning** [comment]
Ansible playbook now based on Raspberry Pi OS Lite 64 bits image , **Release date: September 6th 2022** 
Which overrides the orginal intent of this issue.
