### ISSUE TITLE
WiFi client limitation

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#99]
We were made aware of a wifi limitation. Only 5 clients can connect to the RPI AP at once. This hinders our operation at the schools and a solution is urgently required.

**Comment by joostdam** [comment]
Ik ben er een beetje ingedoken, maar ik kan op dit moment de situatie met meer dan 6 devices niet nabootsen.

Test
Zou jij voor mij het volgende willen doen:
1.	Sudo bash
2.	echo options brcmfmac debug=0x100000 > /etc/modprobe.d/brcmfmac.conf
3.	reboot de pi
4.	connect tot het stopt 
5.	dmesg | grep brcm >log.txt
6.	stuur mij de log.txt

de brcmfmac.conf file zet de debug mode aan. Hiermee zouden we gedetailleerdere meldingen moeten krijgen. Hiermee kan ik het probleem verder uitzoeken.
Voorlopige conclusie:
In de loop der tijd zijn de firmwares voor de wifi aangepast. Hiermee zijn het aantal WiFi clients naar beneden bijgesteld. Dit is dan ook nog afhankelijk van welke exacte chipset er op de Pi zit. Al met al erg onduidelijk.

Vervolg aanpak:
1.	Kijken of er een (oudere) firmware is die meer clients ondersteunde
2.	Kijken of we de firmware kunnen configureren voor meer clients (ben ik nu naar aan het kijken)
3.	Kijken of we de firmware kunnen hercompileren met meer clients (ben ik nu naar aan het kijken)
4.	Last resort: op zoek naar een USB WiFi dongle met een betere driver die meer clients ondersteund.  

Peter Venis

**Comment by joostdam** [comment]
Update van Peter Venis: iemand heeft al deze aanpassing gedaan en volgens 
[firmware-nonfree/debian/config/brcm80211/cypress at bullseye · RPi-Distro/firmware-nonfree · GitHub](https://github.com/RPi-Distro/firmware-nonfree/tree/bullseye/debian/config/brcm80211/cypress)
kan deze driver tot 19 clients aan.

**Comment by joostdam** [comment]
Er zijn meer mensen met dit issue: https://github.com/raspberrypi/linux/issues/3010, het begint met de RPI3 maar later in het draadje ook mensen die hetzelfde ervaren met een RPI4.

**Comment by ltoning** [comment]
> Update van Peter Venis: iemand heeft al deze aanpassing gedaan en volgens [firmware-nonfree/debian/config/brcm80211/cypress at bullseye · RPi-Distro/firmware-nonfree · GitHub](https://github.com/RPi-Distro/firmware-nonfree/tree/bullseye/debian/config/brcm80211/cypress) kan deze driver tot 19 clients aan.
> 
> Joost Dam: het volgende gedaan:
> 
> 1. Bestand cyfmac43455-sdio-minimal.bin in brcm map gekopieerd
> 2. sudo ln -sf ./cypress/cyfmac43455-sdio-minimal.bin brcmfmac43455-sdio.bin
> 3. reboot
> 
> Hierna is het elimu netwerk niet meer zichtbaar.

@joostdam 
 Heb een test gedaan en stap 2. staat verkeerd beschreven dit moet zijn (extra punt aka ../cypress.
 Daarna werkt het Elumipi AP.
 
  2. sudo ln -sf **..**/cypress/cyfmac43455-sdio-minimal.bin brcmfmac43455-sdio.bin

**Comment by joostdam** [comment]
Test gedaan, met extra punt. Wifi AP komt nu wel gewoon op, maar ik kan nog steeds maar 5 apparaten aansluiten.

**Comment by ltoning** [comment]
Tests with the cyfmac43455-sdio-minimal.bin firmeware where succesfull supporting > 11 devices.
Will create a bugfix release of the emulipi image

pi@elimupi:~ $ sudo update-alternatives --config cyfmac43455-sdio.bin
There are 2 choices for the alternative cyfmac43455-sdio.bin (providing /lib/firmware/cypress/cyfmac43455-sdio.bin).

  Selection    Path                                                 Priority   Status
------------------------------------------------------------
* 0            /lib/firmware/cypress/cyfmac43455-sdio-standard.bin   50        auto mode
  1            /lib/firmware/cypress/cyfmac43455-sdio-minimal.bin    10        manual mode
  2            /lib/firmware/cypress/cyfmac43455-sdio-standard.bin   50        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /lib/firmware/cypress/cyfmac43455-sdio-minimal.bin to provide /lib/firmware/cypress/cyfmac43455-sdio.bin (cyfmac43455-sdio.bin) in manual mode

Reboot nu.

 


pi@elimupi:~ $ dmesg | grep -i firmware
[    0.108396] raspberrypi-firmware soc:firmware: Attached to firmware from 2022-08-26T14:03:16, variant start
[    0.112415] raspberrypi-firmware soc:firmware: Firmware hash is 102f1e848393c2112206fadffaaf86db04e98326
[    6.987131] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Nov  1 2021 00:37:12 version 7.45.241 (1a2f2fa CY) FWID 01-5209c09

 


pi@elimupi:~ $ strings  /lib/firmware/cypress/cyfmac43455-sdio-minimal.bin | grep -i version
%s: unsupported bdc protocol version (%d)
wl%d: %s %s version %s FWID 01-%x
wl%d: %s: rsn-ie version (%d) mismatch
43455c0-roml/43455_sdio-pno-aoe-pktfilter-pktctx-lpc-pwropt-txbf-wl11u-wfds-mfp-wowlpf-idsup-idauth-maxclients-noclminc-clm_min Version: 7.45.241 (1a2f2fa CY) CRC: 349757d5 Date: Mon 2021-11-01 00:40:07 PDT Ucode Ver: 1043.2164 FWID 01-5209c09

Onderstaande komt overeen met jouw snapshot afgaand op  FWID 01-703fd60

pi@elimupi:~ $ strings  /lib/firmware/cypress/cyfmac43455-sdio-standard.bin | grep -i version
%s: unsupported bdc protocol version (%d)
wl%d: %s %s version %s FWID 01-%x
wl%d: %s: rsn-ie version (%d) mismatch
Driver version mismatch. expected = %d, got = %d
43455c0-roml/43455_sdio-pno-aoe-pktfilter-pktctx-lpc-pwropt-43455_ftrs-wfds-mfp-dfsradar-wowlpf-idsup-idauth-noclminc-clm_min-obss-obssdump-swdiv Version: 7.45.241 (1a2f2fa CY) CRC: 959ad1c7 Date: Mon 2021-11-01 00:40:29 PDT Ucode Ver: 1043.2164 FWID 01-703fd60
pi@elimupi

**Comment by joostdam** [comment]
Het nieuwe image met de fix werkt. Ik heb het kunnen testen tot 11 clients. Komende week test in Kenia op de scholen.

**Comment by ltoning** [comment]
Issue fixed in ElimuPi release v3.2.1
